# Generated by Django 3.2.9 on 2022-02-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela_venda',
            name='tabela_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='lista.tabela_cliente', verbose_name='id_cliente'),
        ),
        migrations.AlterField(
            model_name='tabela_venda',
            name='dia_venda',
            field=models.CharField(max_length=14),
        ),
    ]
