# Generated by Django 3.2.9 on 2022-02-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela_venda',
            old_name='id_nome',
            new_name='tabela_nome',
        ),
    ]
