# Generated by Django 4.0.2 on 2022-02-17 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_auto_20220216_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabela_venda',
            name='dia_venda',
        ),
        migrations.AlterField(
            model_name='tabela_produto',
            name='preco_total',
            field=models.CharField(max_length=50, verbose_name='Preço_total !$'),
        ),
        migrations.AlterField(
            model_name='tabela_produto',
            name='preco_unidade',
            field=models.CharField(max_length=50, verbose_name='Preço_unidade !$'),
        ),
        migrations.AlterField(
            model_name='tabela_venda',
            name='tabela_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.tabela_cliente', verbose_name='id_cliente'),
        ),
    ]
