# Generated by Django 3.2.9 on 2022-02-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_rename_id_nome_tabela_venda_tabela_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela_venda',
            old_name='tabela_nome',
            new_name='tabela_id',
        ),
        migrations.AddField(
            model_name='tabela_venda',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lista.tabela_produto'),
        ),
        migrations.CreateModel(
            name='venda_possui_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('list', models.ManyToManyField(to='lista.tabela_venda')),
            ],
        ),
    ]
