# Generated by Django 3.2.9 on 2022-02-18 10:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_auto_20220216_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabela_venda',
            name='dia_venda',
        ),
        migrations.AddField(
            model_name='tabela_cliente',
            name='id_cliente',
            field=models.Field(default=6, verbose_name=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='tabela_produto',
            name='id_produto',
            field=models.Field(default=6, verbose_name=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='tabela_venda',
            name='id_venda',
            field=models.Field(default=1, verbose_name=uuid.uuid1),
        ),
        migrations.AlterField(
            model_name='tabela_venda',
            name='tabela_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.tabela_cliente', verbose_name='id_cliente'),
        ),
    ]
