# Generated by Django 3.2.9 on 2022-02-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_auto_20220218_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabela_cliente',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='tabela_produto',
            name='id_produto',
        ),
        migrations.RemoveField(
            model_name='tabela_venda',
            name='id_venda',
        ),
    ]
