# Generated by Django 4.0.2 on 2022-02-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_remove_tabela_venda_dia_venda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabela_venda',
            name='tabela_id',
        ),
        migrations.AddField(
            model_name='tabela_venda',
            name='tabela_nome',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='lista.tabela_cliente'),
            preserve_default=False,
        ),
    ]
