# Generated by Django 4.0.2 on 2022-02-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0005_tabela_venda_teste_alter_tabela_venda_tabela_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabela_venda',
            name='teste',
        ),
        migrations.AlterField(
            model_name='tabela_venda',
            name='tabela_nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.tabela_cliente'),
        ),
    ]
